# Generated by Django 3.1.4 on 2021-01-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomeexpense', '0002_auto_20210103_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='income',
            name='userID',
        ),
    ]
