# Generated by Django 3.1.4 on 2021-01-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeexpense', '0006_auto_20210129_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
    ]
