# Generated by Django 3.1.4 on 2021-02-21 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomeexpense', '0010_reminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
