# Generated by Django 3.1.4 on 2021-02-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomeexpense', '0013_auto_20210228_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='total_income',
        ),
    ]
