# Generated by Django 3.1.4 on 2021-03-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeexpense', '0014_remove_income_total_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='total_income',
            field=models.FloatField(default=0),
        ),
    ]
