# Generated by Django 3.1.4 on 2021-03-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomeexpense', '0016_auto_20210302_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='total_income',
        ),
    ]
